import type { NodeData, Port } from '../types/NodeTypes';

export interface NodeDefinition {
    type: NodeData['type'];
    name: string; // For search box
    label: string; // For UI buttons
    icon: string;
    color: [string, string]; // Gradient for button
    shadow: string; // RGB for box shadow
    initialData: Partial<NodeData['data']>;
    effectColor: string;
}

const SINGLE_TRANSFORM_INPUT: Port[] = [
    { id: 'input-transform', label: 'Transform', type: 'Matrix' },
];

const createCommonGeometryOutput = (): Port[] => [{ id: 'output-geometry', label: 'Geometry', type: 'Mesh' }];
const AI_AGENT_INPUT_PORT: Port = { id: 'input-agent', label: 'Input', type: 'Data' };

const BASE_INITIAL_DATA: Partial<NodeData['data']> = {
    scale: { x: 1, y: 1, z: 1 },
    rotation: { x: 0, y: 0, z: 0 },
    location: { x: 0, y: 0, z: 0 },
};

const HIDE_MODIFIER_AND_PORT_CONTROLS_DATA = {
    hideInputsAdd: true,
    hideOutputsAdd: true,
    hideModifierMenu: true,
    hidePortControls: true,
};

const HIDE_ADD_AND_PORT_CONTROLS_DATA = {
    hideInputsAdd: true,
    hideOutputsAdd: true,
    hidePortControls: true,
};

const UI_WINDOW_DATA = {
    hideInputs: true,
    hideOutputs: true,
    hideOutputsAdd: true,
    hideOutputsHeader: true,
    hidePortControls: true,
    resizable: false,
};


export const NODE_DEFINITIONS: Record<NodeData['type'], NodeDefinition> = {
    'box': {
        type: 'box',
        name: 'Box',
        label: 'Box Node',
        icon: '\u{1F4E6}',
        color: ['#646cff', '#535bf2'],
        shadow: '100, 108, 255',
        initialData: {
            version: 2,
            width: 230,
            inputs: [...SINGLE_TRANSFORM_INPUT, { id: 'input-corner', label: 'Corner', type: 'Number' }],
            outputs: createCommonGeometryOutput(),
            ...HIDE_MODIFIER_AND_PORT_CONTROLS_DATA,
            color: '#cccccc',
        },
        effectColor: '#646cff',
    },
    'sphere': {
        type: 'sphere',
        name: 'Sphere',
        label: 'Sphere Node',
        icon: '\u{1F535}',
        color: ['#2196f3', '#1976d2'],
        shadow: '33, 150, 243',
        initialData: {
            version: 2,
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            inputs: SINGLE_TRANSFORM_INPUT,
            outputs: createCommonGeometryOutput(),
            ...HIDE_MODIFIER_AND_PORT_CONTROLS_DATA,
            color: '#cccccc',
        },
        effectColor: '#2196f3',
    },
    'cone': {
        type: 'cone',
        name: 'Cone',
        label: 'Cone Node',
        icon: '🔼',
        color: ['#8b5cf6', '#7c3aed'],
        shadow: '139, 92, 246',
        initialData: {
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            inputs: [
                ...SINGLE_TRANSFORM_INPUT,
                { id: 'input-radius', label: 'Radius', type: 'Number' },
                { id: 'input-length', label: 'Length', type: 'Number' },
                { id: 'input-corner', label: 'Corner', type: 'Number' },
            ],
            outputs: createCommonGeometryOutput(),
            ...HIDE_MODIFIER_AND_PORT_CONTROLS_DATA,
            radius: 1.0,
            length: 2.0,
            corner: 0.0,
            color: '#cccccc',
        },
        effectColor: '#8b5cf6',
    },
    'cylinder': {
        type: 'cylinder',
        name: 'Cylinder',
        label: 'Cylinder Node',
        icon: 'CY',
        color: ['#0ea5a4', '#0f766e'],
        shadow: '14, 165, 164',
        initialData: {
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            inputs: [
                ...SINGLE_TRANSFORM_INPUT,
                { id: 'input-radius', label: 'Radius', type: 'Number' },
                { id: 'input-length', label: 'Length', type: 'Number' },
                { id: 'input-corner', label: 'Corner', type: 'Number' },
            ],
            outputs: createCommonGeometryOutput(),
            ...HIDE_MODIFIER_AND_PORT_CONTROLS_DATA,
            radius: 1.0,
            length: 2.0,
            corner: 0.0,
            color: '#cccccc',
        },
        effectColor: '#0ea5a4',
    },
    'vector-xyz': {
        type: 'vector-xyz',
        name: 'Vector XYZ',
        label: 'Vector XYZ',
        icon: 'V3',
        color: ['#34d399', '#059669'],
        shadow: '52, 211, 153',
        initialData: {
            customName: 'Vector XYZ',
            icon: 'V3',
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            inputs: [
                { id: 'X', label: 'X component', type: 'Number' },
                { id: 'Y', label: 'Y component', type: 'Number' },
                { id: 'Z', label: 'Z component', type: 'Number' },
            ],
            outputs: [
                { id: 'V', label: 'Vector', type: 'Vector' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#34d399',
    },
    'transform': {
        type: 'transform',
        name: 'Transform',
        label: 'Transform',
        icon: 'TR',
        color: ['#22c55e', '#16a34a'],
        shadow: '34, 197, 94',
        initialData: {
            customName: 'Transform',
            width: 420,
            height: 220,
            location: { x: 0, y: 0, z: 0 },
            rotation: { x: 0, y: 0, z: 0 },
            scale: { x: 1, y: 1, z: 1 },
            inputs: [
                { id: 'move_in', label: 'Move', type: 'Vector' },
                { id: 'rotate_in', label: 'Rotate', type: 'Vector' },
                { id: 'scale_in', label: 'Scale', type: 'Vector' },
            ],
            outputs: [
                { id: 'move_out', label: 'Move', type: 'Vector' },
                { id: 'rotate_out', label: 'Rotate', type: 'Vector' },
                { id: 'scale_out', label: 'Scale', type: 'Vector' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            hideModifierMenu: true,
            hidePortLabels: true,
            hideInputsHeader: true,
            hideOutputsHeader: true,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            bodyPadding: '12px 16px 14px 16px',
            bodyMinHeight: 180,
            inputsAreaWidth: 26,
            outputsAreaWidth: 26,
            inputListTopPadding: 2,
            outputListTopPadding: 2,
            inputRowMinHeight: 40,
            outputRowMinHeight: 40,
            inputRowGap: 8,
            outputRowGap: 8,
            inputRowPaddingY: 0,
            outputRowPaddingY: 0,
        },
        effectColor: '#22c55e',
    },
    'build-3d-ai': {
        type: 'build-3d-ai',
        name: 'Build 3D AI',
        label: 'Build 3D AI',
        icon: '🤖',
        color: ['#10b981', '#059669'],
        shadow: '16, 185, 129',
        initialData: {
            customName: 'Build 3D AI',
            icon: '🤖',
            width: 230,
            inputs: [
                { id: 'input-scope', label: 'Scope', type: 'Bounds' },
                { id: 'input-transform', label: 'Transform', type: 'Matrix' },
            ],
            outputs: [
                { id: 'output-geometry', label: 'Geometry', type: 'Mesh' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hideModifierMenu: true,
            hidePortControls: true,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
        },
        effectColor: '#10b981',
    },
    'ai-agent': {
        type: 'ai-agent',
        name: 'AI Agent',
        label: 'AI Agent',
        icon: '\u{1F9E0}',
        color: ['#f97316', '#ea580c'],
        shadow: '249, 115, 22',
        initialData: {
            customName: 'AI Agent',
            width: 144,
            height: 144,
            agentType: 'phraram',
            portMode: 'input',
            inputs: [AI_AGENT_INPUT_PORT],
            outputs: [],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            hideModifierMenu: true,
            hideInputsHeader: true,
            hideOutputsHeader: true,
            hidePortLabels: true,
            resizable: false,
        },
        effectColor: '#f97316',
    },
    'vertex-mask': {
        type: 'vertex-mask',
        name: 'Vertex Mask',
        label: 'Vertex Mask',
        icon: '\u{1F3AD}',
        color: ['#e879f9', '#c026d3'],
        shadow: '232, 121, 249',
        initialData: {
            customName: 'Vertex Mask',
            icon: '\u{1F3AD}',
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            radius: 0.05,
            value: [],
            inputs: [
                { id: 'input-radius', label: 'Radius', type: 'Number' },
                { id: 'input-smooth', label: 'Smooth', type: 'Boolean' },
                { id: 'input-hit', label: 'Hit', type: 'Boolean' },
                { id: 'input-erase', label: 'Erase', type: 'Boolean' },
            ],
            outputs: [
                { id: 'output-mask', label: 'Mask Mark', type: 'VertexColor' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#e879f9',
    },
    'ai-sculpt': {
        type: 'ai-sculpt',
        name: 'AI Sculpt',
        label: 'AI Sculpt',
        icon: '\u{1F5FF}',
        color: ['#f97316', '#ea580c'],
        shadow: '249, 115, 22',
        initialData: {
            customName: 'AI Sculpt',
            icon: '\u{1F5FF}',
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 80,
            inputs: [
                { id: 'input-mesh', label: 'Mesh Union', type: 'Mesh' },
                { id: 'input-plan', label: 'Sculpt Plan', type: 'Plan' },
                { id: 'input-mask', label: 'Mask Mark', type: 'VertexColor' },
            ],
            outputs: [
                { id: 'output-mesh', label: 'Mesh Result', type: 'Mesh' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#f97316',
    },
    'ai-paint': {
        type: 'ai-paint',
        name: 'AI Paint',
        label: 'AI Paint',
        icon: '\u{1F3A8}',
        color: ['#ec4899', '#db2777'],
        shadow: '236, 72, 153',
        initialData: {
            customName: 'AI Paint',
            icon: '\u{1F3A8}',
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 80,
            inputs: [
                { id: 'input-mesh', label: 'Mesh Union', type: 'Mesh' },
                { id: 'input-plan', label: 'Paint Plan', type: 'Plan' },
                { id: 'input-mask', label: 'Mask Mark', type: 'VertexColor' },
            ],
            outputs: [
                { id: 'output-mesh', label: 'Mesh Painted', type: 'Mesh' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#ec4899',
    },
    'picture-on-mesh': {
        type: 'picture-on-mesh',
        name: 'Picture on Mesh',
        label: 'Picture on Mesh',
        icon: '\u{1F5BC}\uFE0F',
        color: ['#06b6d4', '#0891b2'],
        shadow: '6, 182, 212',
        initialData: {
            customName: 'Picture on Mesh',
            icon: '\u{1F5BC}\uFE0F',
            width: 300,
            minWidth: 300,
            bodyPadding: '14px 20px 10px 0px',
            bodyMinHeight: 120,
            pictureImage: null,
            pictureHit: false,
            pictureErase: false,
            pictureSmooth: false,
            pictureLayerId: 'default',
            inputs: [
                { id: 'context-mesh', label: 'Mesh Union', type: 'Mesh' },
            ],
            outputs: [],
            hideInputsHeader: true,
            hideOutputs: true,
            hideOutputsHeader: true,
            hidePortLabels: true,
            inputsAreaWidth: 1,
            inputPortOffsetLeft: -10,
            inputRowMinHeight: 20,
            inputRowPaddingY: 0,
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#06b6d4',
    },
    'mesh-union': {
        type: 'mesh-union',
        name: 'Mesh Union',
        label: 'Mesh Union',
        icon: '\u{1F9F1}',
        color: ['#f97316', '#ea580c'],
        shadow: '249, 115, 22',
        initialData: {
            customName: 'Mesh Union',
            icon: '\u{1F9F1}',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            inputs: [
                { id: 'M', label: 'Meshes', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
            smoothness: 0.5,
        },
        effectColor: '#f97316',
    },
    'mesh-difference': {
        type: 'mesh-difference',
        name: 'Mesh Difference',
        label: 'Mesh Difference',
        icon: '\u{1F9E9}',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Mesh Difference',
            icon: '\u{1F9E9}',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [
                { id: 'A', label: 'Meshes A', type: 'Mesh' },
                { id: 'B', label: 'Meshes B', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' },
                { id: 'showMeshesB', label: 'Show B', type: 'Boolean' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
            smoothness: 0.15,
            showMeshesB: false,
        },
        effectColor: '#f59e0b',
    },
    'mesh-intersection': {
        type: 'mesh-intersection',
        name: 'Mesh Intersection',
        label: 'Mesh Intersection',
        icon: '\u2229',
        color: ['#22c55e', '#16a34a'],
        shadow: '34, 197, 94',
        initialData: {
            customName: 'Mesh Intersection',
            icon: '\u2229',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [
                { id: 'A', label: 'Meshes A', type: 'Mesh' },
                { id: 'B', label: 'Meshes B', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' },
                { id: 'showMeshesAB', label: 'Show A,B', type: 'Boolean' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
            meshIntersectionMode: 'intersect',
            smoothness: 0.5,
            showMeshesAB: false,
        },
        effectColor: '#22c55e',
    },
    'model-material': {
        type: 'model-material',
        name: 'Model Material',
        label: 'Model Material',
        icon: '\u{1F3A8}',
        color: ['#94a3b8', '#64748b'],
        shadow: '148, 163, 184',
        initialData: {
            customName: 'Model Material',
            icon: '\u{1F3A8}',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            showMaterialPreview: true,
            inputs: [
                { id: 'in-M', label: 'Material', type: 'Model Material' },
                { id: 'in-N', label: 'Name', type: 'Text' },
            ],
            outputs: [
                { id: 'out-M', label: 'Material', type: 'Model Material' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#94a3b8',
    },
    'text-on-mesh': {
        type: 'text-on-mesh',
        name: 'Text On Mesh',
        label: 'Text On Mesh',
        icon: '\u{1F524}',
        color: ['#a855f7', '#7c3aed'],
        shadow: '168, 85, 247',
        initialData: {
            customName: 'Text On Mesh',
            icon: '\u{1F524}',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
            text: 'Hello',
            font: 'Arial',
            textHeight: 10,
            textDepth: 2,
            inputs: [
                { id: 'input-base-mesh', label: 'Base Mesh', type: 'Data' },
                { id: 'input-text', label: 'Text', type: 'Text' },
                { id: 'input-font', label: 'Font', type: 'Text' },
                { id: 'input-height', label: 'Height', type: 'Number' },
                { id: 'input-depth', label: 'Depth', type: 'Number' },
            ],
            outputs: [
                { id: 'output-symbols', label: 'Symbols', type: 'Mesh' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#a855f7',
    },
    'mesh-array': {
        type: 'mesh-array',
        name: 'Mesh Array',
        label: 'Mesh Array',
        icon: 'AR',
        color: ['#c084fc', '#a855f7'],
        shadow: '192, 132, 252',
        initialData: {
            customName: 'Mesh Array',
            icon: 'AR',
            width: 280,
            meshArrayMode: 'linear',
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'input-direction', label: 'Direction', type: 'Vector' },
                { id: 'input-count', label: 'Count', type: 'Integer' },
            ],
            outputs: [
                { id: 'output-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'output-transform', label: 'Transform', type: 'Transform' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#c084fc',
    },
    'mesh-eval': {
        type: 'mesh-eval',
        name: 'Mesh Eval',
        label: 'Mesh Eval',
        icon: 'ME',
        color: ['#a78bfa', '#8b5cf6'],
        shadow: '167, 139, 250',
        initialData: {
            customName: 'Mesh Eval',
            icon: 'ME',
            width: 340,
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'input-parameter', label: 'Parameter', type: 'Mesh Parameter' },
            ],
            outputs: [
                { id: 'output-point', label: 'Point', type: 'Point' },
                { id: 'output-normal', label: 'Normal', type: 'Vector' },
                { id: 'output-colour', label: 'Colour', type: 'Colour' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#a78bfa',
    },
    'face-normals': {
        type: 'face-normals',
        name: 'Face Normals',
        label: 'Face Normals',
        icon: 'FN',
        color: ['#93c5fd', '#60a5fa'],
        shadow: '147, 197, 253',
        initialData: {
            customName: 'Face Normals',
            icon: 'FN',
            width: 340,
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
            ],
            outputs: [
                { id: 'output-centers', label: 'Centers', type: 'Point' },
                { id: 'output-normals', label: 'Normals', type: 'Vector' },
            ],
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#93c5fd',
    },
    'custom': {
        type: 'custom',
        name: 'Custom',
        label: 'Custom',
        icon: '\u2699\uFE0F',
        color: ['#8b5cf6', '#7c3aed'],
        shadow: '139, 92, 246',
        initialData: {
            customName: 'Custom Node',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [],
            outputs: [],
        },
        effectColor: '#8b5cf6',
    },
    'antivirus': {
        type: 'antivirus',
        name: 'AntiVirus',
        label: 'AntiVirus',
        icon: '\u{1F6E1}\uFE0F',
        color: ['#dc2626', '#fca5a5'],
        shadow: '220, 38, 38',
        initialData: {
            customName: 'AntiVirus Node',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [],
            outputs: [],
        },
        effectColor: '#dc2626',
    },
    'input': {
        type: 'input',
        name: 'Input',
        label: 'Input',
        icon: '📥',
        color: ['#22c55e', '#16a34a'],
        shadow: '34, 197, 94',
        initialData: {
            customName: 'Input Node',
            width: 200,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [],
            outputs: [{ id: 'output-1', label: 'Output 1' }],
            hideTitleLabel: true,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
        },
        effectColor: '#22c55e',
    },
    'output': {
        type: 'output',
        name: 'Output',
        label: 'Output',
        icon: '📤',
        color: ['#ef4444', '#dc2626'],
        shadow: '239, 68, 68',
        initialData: {
            customName: 'Output Node',
            width: 200,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [{ id: 'input-1', label: 'Input 1' }],
            outputs: [],
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hideTitleLabel: true,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 60,
        },
        effectColor: '#ef4444',
    },
    'number-slider': {
        type: 'number-slider',
        name: 'Number Slider',
        label: 'Number Slider',
        icon: 'NS',
        color: ['#0ea5e9', '#0284c7'],
        shadow: '14, 165, 233',
        initialData: {
            customName: 'Number Slider',
            width: 420,
            height: 190,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 4,
            useGlobalConfig: true,
            globalMin: 0,
            globalMax: 100,
            globalStep: 1,
            sliders: [{ id: 'slider-1', value: 50, min: 0, max: 100, step: 1 }],
            value: [50],
            inputs: [],
            outputs: [{ id: 'output-main', label: 'Value' }],
        },
        effectColor: '#0ea5e9',
    },
    'boolean-toggle': {
        type: 'boolean-toggle',
        name: 'Boolean Toggle',
        label: 'Boolean Toggle',
        icon: 'BT',
        color: ['#10b981', '#059669'],
        shadow: '16, 185, 129',
        initialData: {
            customName: 'Boolean Toggle',
            width: 160,
            height: 100,
            value: false,
            toggles: [{ id: 'toggle_1', value: false }],
            toggleNextId: 2,
            inputs: [],
            outputs: [{ id: 'out_1', label: 'Bool #1', type: 'Boolean' }],
            hideInputs: true,
            ...HIDE_ADD_AND_PORT_CONTROLS_DATA,
        },
        effectColor: '#10b981',
    },
    'series': {
        type: 'series',
        name: 'Series',
        label: 'Series',
        icon: 'SR',
        color: ['#14b8a6', '#0f766e'],
        shadow: '20, 184, 166',
        initialData: {
            customName: 'Series',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            start: 0,
            step: 1,
            count: 10,
            inputs: [
                { id: 'input-start', label: 'Start' },
                { id: 'input-step', label: 'Step' },
                { id: 'input-count', label: 'Count' },
            ],
            outputs: [{ id: 'output-series', label: 'Series' }],
            bodyPadding: '46px 20px 24px 20px',
            bodyMinHeight: 60,
        },
        effectColor: '#14b8a6',
    },
    'panel': {
        type: 'panel',
        name: 'Inspector',
        label: 'Inspector',
        icon: '👁️',
        color: ['#eab308', '#ca8a04'],
        shadow: '234, 179, 8',
        initialData: {
            customName: 'Inspector',
            width: 300,
            height: 220,
            isPaused: false,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [{ id: 'input-main', label: 'Inspector Input' }],
            outputs: [{ id: 'output-main', label: 'Inspector Output' }],
        },
        effectColor: '#eab308',
    },
    'node-prompt': {
        type: 'node-prompt',
        name: 'Text Data',
        label: 'Text Data',
        icon: '\u{1F4AC}',
        color: ['#22d3ee', '#0ea5e9'],
        shadow: '34, 211, 238',
        initialData: {
            customName: 'Text Data',
            width: 300,
            height: 240,
            minWidth: 160,
            bodyMinHeight: 140,
            promptText: '',
            isGenerating: false,
            promptStatus: 'idle',
            promptError: '',
            stopGenerationToken: 0,
            chatSessions: [
                { id: 'default', title: 'New Chat', messages: [], timestamp: Date.now() }
            ],
            activeSessionId: 'default',
            pendingImages: [],
            chatModel: 'model-a',
            chatActionMode: 'plan',
            outputs: [{ id: 'output-prompt', label: 'Text', type: 'Text' }],
            hideInputs: true,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortControls: true,
            hidePortLabels: true,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputsAreaWidth: 20,
            bodyPadding: '10px 4px 14px 14px',
            planContent: '',
            planMarkdown: '',
            planSource: 'ai',
        },
        effectColor: '#22d3ee',
    },
    'background-color': {
        type: 'background-color',
        name: 'Background color',
        label: 'Background color',
        icon: 'BG',
        color: ['#475569', '#1f2937'],
        shadow: '71, 85, 105',
        initialData: {
            customName: 'Background color',
            width: 230,
            height: 190,
            backgroundColor: '#1e1e1e',
            backgroundMode: 'solid',
            backgroundGradientStart: '#0f172a',
            backgroundGradientEnd: '#1f2937',
            backgroundGradientAngle: 135,
            inputs: [],
            outputs: [{ id: 'output-background', label: 'Background', type: 'Color' }],
            ...UI_WINDOW_DATA,
            hideOutputs: false,
            hidePortLabels: true,
            outputsAreaWidth: 14,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 2,
            outputListTopPadding: 0,
            outputRowMinHeight: 100,
            outputRowGap: 0,
            outputRowPaddingY: 0,
        },
        effectColor: '#475569',
    },
    'viewport': {
        type: 'viewport',
        name: 'Viewport',
        label: 'Viewport',
        icon: 'VP',
        color: ['#22d3ee', '#0ea5e9'],
        shadow: '34, 211, 238',
        initialData: {
            customName: 'Viewport',
            width: 230,
            height: 156,
            viewportMode: 'rendered',
            inputs: [],
            outputs: [{ id: 'output-viewport', label: 'Viewport', type: 'Viewport' }],
            ...UI_WINDOW_DATA,
            hideOutputs: false,
            hidePortLabels: true,
            outputsAreaWidth: 14,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 2,
            outputListTopPadding: 0,
            outputRowMinHeight: 78,
            outputRowGap: 0,
            outputRowPaddingY: 0,
        },
        effectColor: '#22d3ee',
    },
    'widget-window': {
        type: 'widget-window',
        name: 'Widget Window',
        label: 'Widget',
        icon: '🪟',
        color: ['#38bdf8', '#0ea5e9'],
        shadow: '56, 189, 248',
        initialData: {
            customName: 'Widget Window',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            inputs: [],
            outputs: [],
            hideOutputsHeader: true,
            hideOutputsAdd: true,
        },
        effectColor: '#38bdf8',
    },
    'prompt': {
        type: 'prompt',
        name: 'Prompt',
        label: 'Prompt',
        icon: '\u270F\uFE0F',
        color: ['#ef4444', '#dc2626'],
        shadow: '239, 68, 68',
        initialData: {
            customName: 'Prompt',
            icon: '\u270F\uFE0F',
            width: 220,
            height: 125,
            promptDraft: '',
            promptPendingImages: [],
            promptOutput: '',
            inputs: [],
            outputs: [
                { id: 'output-prompt', label: 'Prompt', type: 'String' },
            ],
            hideInputs: true,
            hideInputsHeader: true,
            hideInputsAdd: true,
            hideOutputsHeader: false,
            hideOutputsAdd: true,
            hidePortControls: true,
            hideModifierMenu: true,
            bodyPadding: '30px 12px 10px 12px',
            bodyMinHeight: 22,
            outputsAreaWidth: 62,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            outputListTopPadding: 0,
            outputRowMinHeight: 20,
            outputRowGap: 0,
            outputRowPaddingY: 0,
        },
        effectColor: '#ef4444',
    },
    'ai-assistant': {
        type: 'ai-assistant',
        name: 'AI Assistant',
        label: 'AI Assistant',
        icon: '\u{1F916}',
        color: ['#8b5cf6', '#7c3aed'],
        shadow: '139, 92, 246',
        initialData: {
            customName: 'AI Assistant',
            icon: '\u{1F916}',
            width: 230,
            height: 125,
            panelVisible: true,
            panelPosition: { x: 0, y: 0 },
            panelSize: { width: 350, height: 420 },
            aiAssistantDraft: '',
            aiAssistantResponse: '',
            planContent: '',
            planMarkdown: '',
            planSource: 'ai',
            planPanelVisible: false,
            planPanelWidth: 280,
            inputs: [],
            outputs: [
                { id: 'output-response', label: 'AI Response', type: 'String' },
            ],
            hideInputs: true,
            hideInputsHeader: true,
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            hideModifierMenu: true,
            bodyPadding: '34px 12px 8px 12px',
            bodyMinHeight: 18,
            outputsAreaWidth: 84,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            outputListTopPadding: 0,
            outputRowMinHeight: 22,
            outputRowGap: 0,
            outputRowPaddingY: 0,
        },
        effectColor: '#8b5cf6',
    },
    'layer-source': {
        type: 'layer-source',
        name: 'Layer Source',
        label: 'Layer Source',
        icon: '📑',
        color: ['#fbbf24', '#d97706'],
        shadow: '251, 191, 36',
        initialData: {
            customName: 'Layer Source',
            width: 230,
            inputPortOffsetLeft: -30,
            outputPortSide: 'right',
            outputPortAbsoluteCentered: true,
            outputPortOffsetRight: 10,
            outputLabelMarginRight: 44,
            outputEditMarginRight: 42,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 120,
            inputs: [{ id: 'input-1', label: 'Layer 1' }],
            outputs: [{ id: 'output-1', label: 'Layer Output' }],
        },
        effectColor: '#fbbf24',
    },
    'layer-bridge': {
        type: 'layer-bridge',
        name: 'Layer Bridge',
        label: 'Layer Bridge',
        icon: 'L2B',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Layer Bridge',
            width: 230,
            bodyPadding: '36px 20px 10px 20px',
            bodyMinHeight: 120,
            hideOutputs: true,
            hideOutputsAdd: true,
            hideModifierMenu: true,
            hideOutputsHeader: true,
            inputs: [{ id: 'input-layers', label: 'Layers' }],
            outputs: [],
        },
        effectColor: '#f59e0b',
    },
    'layer-view': {
        type: 'layer-view',
        name: 'Layer View',
        label: 'Layer View',
        icon: 'ALL',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Layer View',
            width: 300,
            height: 300,
            hideInputs: true,
            hideInputsAdd: true,
            hideOutputs: false,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortLabels: true,
            hidePortControls: true,
            centerOutput: true,
            showLayerPanel: true,
            hideLayerPanelToolbar: false,
            hideLayerPanelCheckboxes: true,
            hideLayerPanelIcons: true,
            inputs: [],
            outputs: [
                { id: 'output-all-layer', label: 'AllLayer Output', type: 'data' }
            ],
        },
        effectColor: '#f59e0b',
    },
    'group': {
        type: 'group',
        name: 'Group',
        label: 'Group',
        icon: 'GR',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Group',
            icon: 'GR',
            width: 420,
            height: 260,
            isGroup: true,
            childNodeIds: [],
            inputs: [],
            outputs: [],
        },
        effectColor: '#f59e0b',
    },
    'component': {
        type: 'component',
        name: 'Component',
        label: 'Component',
        icon: '\u{1F9E9}',
        color: ['#60a5fa', '#3b82f6'],
        shadow: '96, 165, 250',
        initialData: {
            customName: 'Component',
            icon: '\u{1F9E9}',
            width: 320,
            inputs: [],
            outputs: [],
        },
        effectColor: '#60a5fa',
    },
    'unit-x': {
        type: 'unit-x',
        name: 'X',
        label: 'X',
        icon: 'X',
        color: ['#ef4444', '#dc2626'], // Red for X axis
        shadow: '239, 68, 68',
        initialData: {
            customName: 'X',
            width: 200,
            inputs: [{ id: 'F', label: 'Factor', type: 'Number' }],
            outputs: [{ id: 'V', label: '', type: 'Vector' }],
            negative: false,
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            outputPortOffsetRight: -15,
        },
        effectColor: '#ef4444',
    },
    'unit-y': {
        type: 'unit-y',
        name: 'Y',
        label: 'Y',
        icon: 'Y',
        color: ['#10b981', '#059669'], // Green-ish for Y axis/Vector
        shadow: '16, 185, 129',
        initialData: {
            customName: 'Y',
            width: 200, // Compact width
            inputs: [{ id: 'F', label: 'Factor', type: 'Number' }],
            outputs: [{ id: 'V', label: '', type: 'Vector' }],
            negative: false,
            // Hiding standard controls to keep it clean, if desired
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            outputPortOffsetRight: -15,
        },
        effectColor: '#10b981',
    },
    'unit-z': {
        type: 'unit-z',
        name: 'Z',
        label: 'Z',
        icon: 'Z',
        color: ['#2563eb', '#1d4ed8'], // Blue for Z axis
        shadow: '37, 99, 235',
        initialData: {
            customName: 'Z',
            width: 200,
            inputs: [{ id: 'F', label: 'Factor', type: 'Number' }],
            outputs: [{ id: 'V', label: '', type: 'Vector' }],
            negative: false,
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            outputPortOffsetRight: -15,
        },
        effectColor: '#2563eb',
    },
};

export const getNodeDefinition = (type: NodeData['type']): NodeDefinition | undefined => {
    return NODE_DEFINITIONS[type];
};

export const getInitialDataForNode = (type: NodeData['type']): Partial<NodeData['data']> => {
    const definition = getNodeDefinition(type);
    const mergedInitialData = {
        ...BASE_INITIAL_DATA,
        ...(definition ? definition.initialData : {}),
    };
    try {
        return structuredClone(mergedInitialData);
    } catch {
        return JSON.parse(JSON.stringify(mergedInitialData)) as Partial<NodeData['data']>;
    }
};
