import type { PlanComparisonRow, PricingPlan } from '../types/pricing.types';

export const PLAN_COMPARISON_ROWS: PlanComparisonRow[] = [
  { id: 'monthlyCredits', label: 'AI Credits / month' },
  { id: 'maxProjects', label: 'Max saved workflows' },
  { id: 'resolution', label: 'Render resolution' },
  { id: 'privateModels', label: 'Private model workspace' },
  { id: 'priorityQueue', label: 'Priority generation queue' },
  { id: 'teamSeats', label: 'Team seats' },
  { id: 'support', label: 'Support level' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    description: 'For solo creators testing idea-to-model workflow quickly.',
    monthlyPrice: 9,
    yearlyPrice: 86,
    currency: 'USD',
    badge: 'For Individuals',
    ctaLabel: 'Choose Starter',
    features: [
      '2.5 Million Tokens / month',
      'Basic AI sculpt and paint assist',
      'Export standard mesh formats',
      'Community support channel',
    ],
    comparison: {
      monthlyCredits: '2.5M Tokens',
      maxProjects: '3',
      resolution: '1080p',
      privateModels: false,
      priorityQueue: false,
      teamSeats: '1',
      support: 'Community',
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Best for daily production work with faster queue and higher limits.',
    monthlyPrice: 19,
    yearlyPrice: 182,
    currency: 'USD',
    badge: 'Popular',
    ctaLabel: 'Choose Pro',
    features: [
      '4 Million Tokens / month',
      'High priority generation queue',
      '4K rendering and richer materials',
      'Prompt libraries + reusable presets',
    ],
    comparison: {
      monthlyCredits: '4.0M Tokens',
      maxProjects: 'Unlimited',
      resolution: '4K',
      privateModels: true,
      priorityQueue: true,
      teamSeats: '3',
      support: 'Priority email',
    },
  },
  {
    id: 'studio',
    name: 'Studio',
    description: 'For teams needing shared governance and advanced collaboration.',
    monthlyPrice: 39,
    yearlyPrice: 374,
    currency: 'USD',
    badge: 'Most Popular',
    recommended: true,
    ctaLabel: 'Choose Studio',
    features: [
      '6 Million Tokens / month',
      'Dedicated queue allocation',
      'Versioned libraries and project templates',
      'SLA-backed technical support',
    ],
    comparison: {
      monthlyCredits: '6.0M Tokens',
      maxProjects: 'Unlimited',
      resolution: '4K + batch export',
      privateModels: true,
      priorityQueue: true,
      teamSeats: '10',
      support: 'SLA + onboarding',
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Custom infrastructure and highest limits for large scale organizations.',
    monthlyPrice: 69,
    yearlyPrice: 662,
    currency: 'USD',
    badge: 'Max Usage',
    ctaLabel: 'Choose Enterprise',
    features: [
      '15 Million Tokens / month',
      'Dedicated compute instances',
      'Advanced API access & webhooks',
      '24/7 dedicated account manager',
    ],
    comparison: {
      monthlyCredits: '15.0M Tokens',
      maxProjects: 'Unlimited',
      resolution: '8K + batch export',
      privateModels: true,
      priorityQueue: true,
      teamSeats: 'Unlimited',
      support: '24/7 Dedicated',
    },
  },
];

export const DEFAULT_PLAN_ID = 'pro';
