import type { PlanComparisonRow, PricingPlan } from '../types/pricing.types';

export const PLAN_COMPARISON_ROWS: PlanComparisonRow[] = [
  { id: 'monthlyCredits', label: 'AI Credits / month' },
  { id: 'maxProjects', label: 'Max saved workflows' },
  { id: 'resolution', label: 'Render resolution' },
  { id: 'privateModels', label: 'Private model workspace' },
  { id: 'priorityQueue', label: 'Priority generation queue' },
  { id: 'teamSeats', label: 'Team seats' },
  { id: 'support', label: 'Support level' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Starter sandbox for exploring core workflow before upgrading.',
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: 'THB',
    checkoutEnabled: false,
    badge: 'Community Tier',
    ctaLabel: 'Included',
    features: [
      '1 active project',
      'Basic nodes and manual modeling',
      'Standard mesh export',
      'Community documentation support',
    ],
    comparison: {
      monthlyCredits: '30',
      maxProjects: '1',
      resolution: '720p',
      privateModels: false,
      priorityQueue: false,
      teamSeats: '1',
      support: 'Community docs',
    },
  },
  {
    id: 'starter',
    name: 'Starter',
    description: 'For solo creators testing idea-to-model workflow quickly.',
    monthlyPrice: 490,
    yearlyPrice: 4900,
    currency: 'THB',
    badge: 'For Individuals',
    ctaLabel: 'Choose Starter',
    features: [
      '3 active projects at a time',
      'Basic AI sculpt and paint assist',
      'Export standard mesh formats',
      'Community support channel',
    ],
    comparison: {
      monthlyCredits: '150',
      maxProjects: '3',
      resolution: '1080p',
      privateModels: false,
      priorityQueue: false,
      teamSeats: '1',
      support: 'Community',
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Best for daily production work with faster queue and higher limits.',
    monthlyPrice: 1290,
    yearlyPrice: 12900,
    currency: 'THB',
    badge: 'Most Popular',
    recommended: true,
    ctaLabel: 'Choose Pro',
    features: [
      'Unlimited active projects',
      'High priority generation queue',
      '4K rendering and richer materials',
      'Prompt libraries + reusable presets',
    ],
    comparison: {
      monthlyCredits: '600',
      maxProjects: 'Unlimited',
      resolution: '4K',
      privateModels: true,
      priorityQueue: true,
      teamSeats: '3',
      support: 'Priority email',
    },
  },
  {
    id: 'studio',
    name: 'Studio',
    description: 'For teams needing shared governance and advanced collaboration.',
    monthlyPrice: 2990,
    yearlyPrice: 29900,
    currency: 'THB',
    badge: 'Team Plan',
    ctaLabel: 'Choose Studio',
    features: [
      'Shared workspace with role controls',
      'Dedicated queue allocation',
      'Versioned libraries and project templates',
      'SLA-backed technical support',
    ],
    comparison: {
      monthlyCredits: '1800',
      maxProjects: 'Unlimited',
      resolution: '4K + batch export',
      privateModels: true,
      priorityQueue: true,
      teamSeats: '10',
      support: 'SLA + onboarding',
    },
  },
];

export const DEFAULT_PLAN_ID = 'pro';
