import type { NodeData, Port } from '../types/NodeTypes';

export interface NodeDefinition {
    type: NodeData['type'];
    name: string; // For search box
    label: string; // For UI buttons
    icon: string;
    color: [string, string]; // Gradient for button
    shadow: string; // RGB for box shadow
    initialData: Partial<NodeData['data']>;
    effectColor: string;
}

const COMMON_TRANSFORM_INPUTS: Port[] = [
    { id: 'input-move', label: 'Move' },
    { id: 'input-rotate', label: 'Rotate' },
    { id: 'input-scale', label: 'Scale' },
];

const COMMON_GEOMETRY_OUTPUT: Port[] = [{ id: 'output-geometry', label: 'Geometry', type: 'Mesh' }];

const BASE_INITIAL_DATA: Partial<NodeData['data']> = {
    scale: { x: 1, y: 1, z: 1 },
    rotation: { x: 0, y: 0, z: 0 },
    location: { x: 0, y: 0, z: 0 },
};

export const NODE_DEFINITIONS: Record<NodeData['type'], NodeDefinition> = {
    'box': {
        type: 'box',
        name: 'Box',
        label: 'Box Node',
        icon: '\u{1F4E6}',
        color: ['#646cff', '#535bf2'],
        shadow: '100, 108, 255',
        initialData: {
            width: 300,
            inputs: [...COMMON_TRANSFORM_INPUTS, { id: 'input-corner', label: 'Corner', type: 'Number' }],
            outputs: COMMON_GEOMETRY_OUTPUT,
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hideModifierMenu: true,
            hidePortControls: true,
        },
        effectColor: '#646cff',
    },
    'sphere': {
        type: 'sphere',
        name: 'Sphere',
        label: 'Sphere Node',
        icon: '\u{1F535}',
        color: ['#2196f3', '#1976d2'],
        shadow: '33, 150, 243',
        initialData: {
            width: 300,
            inputs: COMMON_TRANSFORM_INPUTS,
            outputs: COMMON_GEOMETRY_OUTPUT,
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hideModifierMenu: true,
            hidePortControls: true,
        },
        effectColor: '#2196f3',
    },
    'vector-xyz': {
        type: 'vector-xyz',
        name: 'Vecter XYZ',
        label: 'Vecter XYZ',
        icon: 'V3',
        color: ['#34d399', '#059669'],
        shadow: '52, 211, 153',
        initialData: {
            customName: 'Vecter XYZ',
            icon: 'V3',
            width: 300,
            height: 260,
            inputs: [
                { id: 'X', label: 'X component', type: 'Number' },
                { id: 'Y', label: 'Y component', type: 'Number' },
                { id: 'Z', label: 'Z component', type: 'Number' },
            ],
            outputs: [
                { id: 'V', label: 'Vector', type: 'Vector' },
                { id: 'L', label: 'Length', type: 'Number' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#34d399',
    },
    'mesh-union': {
        type: 'mesh-union',
        name: 'Mesh Union',
        label: 'Mesh Union',
        icon: '\u{1F9F1}',
        color: ['#f97316', '#ea580c'],
        shadow: '249, 115, 22',
        initialData: {
            customName: 'Mesh Union',
            icon: '\u{1F9F1}',
            width: 300,
            inputs: [
                { id: 'M', label: 'Meshes', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            smoothness: 0.5,
        },
        effectColor: '#f97316',
    },
    'mesh-difference': {
        type: 'mesh-difference',
        name: 'Mesh Difference',
        label: 'Mesh Difference',
        icon: '\u{1F9E9}',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Mesh Difference',
            icon: '\u{1F9E9}',
            width: 320,
            inputs: [
                { id: 'A', label: 'Meshes A', type: 'Mesh' },
                { id: 'B', label: 'Meshes B', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            smoothness: 0.5,
            showMeshesB: true,
        },
        effectColor: '#f59e0b',
    },
    'mesh-intersection': {
        type: 'mesh-intersection',
        name: 'Mesh Intersection',
        label: 'Mesh Intersection',
        icon: '\u2229',
        color: ['#22c55e', '#16a34a'],
        shadow: '34, 197, 94',
        initialData: {
            customName: 'Mesh Intersection',
            icon: '\u2229',
            width: 320,
            inputs: [
                { id: 'A', label: 'Meshes A', type: 'Mesh' },
                { id: 'B', label: 'Meshes B', type: 'Mesh' },
                { id: 'S', label: 'Smoothness', type: 'Number' }
            ],
            outputs: [{ id: 'R', label: 'Result', type: 'Mesh' }],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
            meshIntersectionMode: 'intersect',
            smoothness: 0.5,
        },
        effectColor: '#22c55e',
    },
    'model-material': {
        type: 'model-material',
        name: 'Model Material',
        label: 'Model Material',
        icon: '\u{1F3A8}',
        color: ['#94a3b8', '#64748b'],
        shadow: '148, 163, 184',
        initialData: {
            customName: 'Model Material',
            icon: '\u{1F3A8}',
            width: 320,
            showMaterialPreview: true,
            inputs: [
                { id: 'in-M', label: 'Material', type: 'Model Material' },
                { id: 'in-N', label: 'Name', type: 'Text' },
            ],
            outputs: [
                { id: 'out-M', label: 'Material', type: 'Model Material' },
                { id: 'out-N', label: 'Name', type: 'Text' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#94a3b8',
    },
    'text-on-mesh': {
        type: 'text-on-mesh',
        name: 'Text On Mesh',
        label: 'Text On Mesh',
        icon: '\u{1F524}',
        color: ['#a855f7', '#7c3aed'],
        shadow: '168, 85, 247',
        initialData: {
            customName: 'Text On Mesh',
            icon: '\u{1F524}',
            width: 360,
            text: 'Hello',
            font: 'Arial',
            textHeight: 10,
            textDepth: 2,
            inputs: [
                { id: 'input-base-mesh', label: 'Base Mesh', type: 'Data' },
                { id: 'input-text', label: 'Text', type: 'Text' },
                { id: 'input-font', label: 'Font', type: 'Text' },
                { id: 'input-height', label: 'Height', type: 'Number' },
                { id: 'input-depth', label: 'Depth', type: 'Number' },
            ],
            outputs: [
                { id: 'output-symbols', label: 'Symbols', type: 'Mesh' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#a855f7',
    },
    'mesh-array': {
        type: 'mesh-array',
        name: 'Mesh Array',
        label: 'Mesh Array',
        icon: 'AR',
        color: ['#c084fc', '#a855f7'],
        shadow: '192, 132, 252',
        initialData: {
            customName: 'Mesh Array',
            icon: 'AR',
            width: 360,
            meshArrayMode: 'linear',
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'input-direction', label: 'Direction', type: 'Vector' },
                { id: 'input-count', label: 'Count', type: 'Integer' },
            ],
            outputs: [
                { id: 'output-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'output-transform', label: 'Transform', type: 'Transform' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#c084fc',
    },
    'mesh-eval': {
        type: 'mesh-eval',
        name: 'Mesh Eval',
        label: 'Mesh Eval',
        icon: 'ME',
        color: ['#a78bfa', '#8b5cf6'],
        shadow: '167, 139, 250',
        initialData: {
            customName: 'Mesh Eval',
            icon: 'ME',
            width: 340,
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
                { id: 'input-parameter', label: 'Parameter', type: 'Mesh Parameter' },
            ],
            outputs: [
                { id: 'output-point', label: 'Point', type: 'Point' },
                { id: 'output-normal', label: 'Normal', type: 'Vector' },
                { id: 'output-colour', label: 'Colour', type: 'Colour' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#a78bfa',
    },
    'face-normals': {
        type: 'face-normals',
        name: 'Face Normals',
        label: 'Face Normals',
        icon: 'FN',
        color: ['#93c5fd', '#60a5fa'],
        shadow: '147, 197, 253',
        initialData: {
            customName: 'Face Normals',
            icon: 'FN',
            width: 340,
            inputs: [
                { id: 'input-mesh', label: 'Mesh', type: 'Mesh' },
            ],
            outputs: [
                { id: 'output-centers', label: 'Centers', type: 'Point' },
                { id: 'output-normals', label: 'Normals', type: 'Vector' },
            ],
            hideInputsAdd: true,
            hideOutputsAdd: true,
            hidePortControls: true,
        },
        effectColor: '#93c5fd',
    },
    'custom': {
        type: 'custom',
        name: 'Custom',
        label: 'Custom',
        icon: '\u2699\uFE0F',
        color: ['#8b5cf6', '#7c3aed'],
        shadow: '139, 92, 246',
        initialData: {
            customName: 'Custom Node',
            width: 300,
            inputs: [],
            outputs: [],
        },
        effectColor: '#8b5cf6',
    },
    'antivirus': {
        type: 'antivirus',
        name: 'AntiVirus',
        label: 'AntiVirus',
        icon: '\u{1F6E1}\uFE0F',
        color: ['#dc2626', '#fca5a5'],
        shadow: '220, 38, 38',
        initialData: {
            customName: 'AntiVirus Node',
            width: 300,
            inputs: [],
            outputs: [],
        },
        effectColor: '#dc2626',
    },
    'input': {
        type: 'input',
        name: 'Input',
        label: 'Input',
        icon: '📥',
        color: ['#22c55e', '#16a34a'],
        shadow: '34, 197, 94',
        initialData: {
            customName: 'Input Node',
            width: 300,
            inputs: [],
            outputs: [{ id: 'output-1', label: 'Output 1' }],
        },
        effectColor: '#22c55e',
    },
    'output': {
        type: 'output',
        name: 'Output',
        label: 'Output',
        icon: '📤',
        color: ['#ef4444', '#dc2626'],
        shadow: '239, 68, 68',
        initialData: {
            customName: 'Output Node',
            width: 300,
            inputs: [{ id: 'input-1', label: 'Input 1' }],
            outputs: [],
        },
        effectColor: '#ef4444',
    },
    'number-slider': {
        type: 'number-slider',
        name: 'Number Slider',
        label: 'Number Slider',
        icon: 'NS',
        color: ['#0ea5e9', '#0284c7'],
        shadow: '14, 165, 233',
        initialData: {
            customName: 'Number Slider',
            width: 360,
            height: 150,
            min: 0,
            max: 100,
            step: 1,
            value: 50,
            inputs: [],
            outputs: [{ id: 'output-main', label: 'Value' }],
        },
        effectColor: '#0ea5e9',
    },
    'series': {
        type: 'series',
        name: 'Series',
        label: 'Series',
        icon: 'SR',
        color: ['#14b8a6', '#0f766e'],
        shadow: '20, 184, 166',
        initialData: {
            customName: 'Series',
            width: 300,
            height: 170,
            start: 0,
            step: 1,
            count: 10,
            inputs: [
                { id: 'input-s', label: 'S' },
                { id: 'input-n', label: 'N' },
                { id: 'input-c', label: 'C' },
            ],
            outputs: [{ id: 'output-series', label: 'Series' }],
        },
        effectColor: '#14b8a6',
    },
    'panel': {
        type: 'panel',
        name: 'Inspector',
        label: 'Inspector',
        icon: '👁️',
        color: ['#eab308', '#ca8a04'],
        shadow: '234, 179, 8',
        initialData: {
            customName: 'Inspector',
            width: 300,
            height: 300,
            isPaused: false,
            inputs: [{ id: 'input-main', label: 'Inspector Input' }],
            outputs: [{ id: 'output-main', label: 'Inspector Output' }],
        },
        effectColor: '#eab308',
    },
    'node-prompt': {
        type: 'node-prompt',
        name: 'Node Prompt',
        label: 'Node Prompt',
        icon: '\u{1F4AC}',
        color: ['#22d3ee', '#0ea5e9'],
        shadow: '34, 211, 238',
        initialData: {
            customName: 'Node Prompt',
            width: 320,
            height: 200,
            promptText: '',
            outputs: [{ id: 'output-prompt', label: 'Prompt', type: 'Text' }],
            hideInputs: true,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortControls: true,
        },
        effectColor: '#22d3ee',
    },
    'background-color': {
        type: 'background-color',
        name: 'BlackGround color',
        label: 'BlackGround color',
        icon: 'BG',
        color: ['#475569', '#1f2937'],
        shadow: '71, 85, 105',
        initialData: {
            customName: 'BlackGround color',
            width: 300,
            height: 160,
            backgroundColor: '#1e1e1e',
            backgroundMode: 'solid',
            backgroundGradientStart: '#0f172a',
            backgroundGradientEnd: '#1f2937',
            backgroundGradientAngle: 135,
            inputs: [],
            outputs: [],
            hideInputs: true,
            hideOutputs: true,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortControls: true,
            resizable: false,
        },
        effectColor: '#475569',
    },
    'viewport': {
        type: 'viewport',
        name: 'Viewport',
        label: 'Viewport',
        icon: 'VP',
        color: ['#22d3ee', '#0ea5e9'],
        shadow: '34, 211, 238',
        initialData: {
            customName: 'Viewport',
            width: 300,
            height: 170,
            viewportMode: 'rendered',
            inputs: [],
            outputs: [],
            hideInputs: true,
            hideOutputs: true,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortControls: true,
            resizable: false,
        },
        effectColor: '#22d3ee',
    },
    'widget-window': {
        type: 'widget-window',
        name: 'Widget Window',
        label: 'Widget',
        icon: '🪟',
        color: ['#38bdf8', '#0ea5e9'],
        shadow: '56, 189, 248',
        initialData: {
            customName: 'Widget Window Mode',
            width: 300,
            height: 280,
            inputs: [],
            outputs: [{ id: 'output-1', label: 'View Output' }],
        },
        effectColor: '#38bdf8',
    },
    'layer-source': {
        type: 'layer-source',
        name: 'Layer Source',
        label: 'Layer Source',
        icon: '📑',
        color: ['#fbbf24', '#d97706'],
        shadow: '251, 191, 36',
        initialData: {
            customName: 'Layer Source',
            width: 300,
            height: 113,
            inputs: [{ id: 'input-1', label: 'Layer Input' }],
            outputs: [{ id: 'output-1', label: 'Layer Output' }],
        },
        effectColor: '#fbbf24',
    },
    'layer-bridge': {
        type: 'layer-bridge',
        name: 'Layer Bridge',
        label: 'Layer Bridge',
        icon: 'L2B',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Layer Bridge',
            width: 300,
            height: 180,
            hideOutputs: true,
            hideOutputsAdd: true,
            hideModifierMenu: true,
            inputs: [{ id: 'input-layers', label: 'Layers' }],
            outputs: [],
        },
        effectColor: '#f59e0b',
    },
    'layer-view': {
        type: 'layer-view',
        name: 'Layer View',
        label: 'Layer View',
        icon: 'ALL',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Layer View',
            width: 300,
            height: 300,
            hideInputs: true,
            hideInputsAdd: true,
            hideOutputs: false,
            hideOutputsAdd: true,
            hideOutputsHeader: true,
            hidePortLabels: true,
            hidePortControls: true,
            centerOutput: true,
            showLayerPanel: true,
            hideLayerPanelToolbar: false,
            hideLayerPanelCheckboxes: true,
            hideLayerPanelIcons: true,
            inputs: [],
            outputs: [
                { id: 'output-all-layer', label: 'AllLayer Output', type: 'data' }
            ],
        },
        effectColor: '#f59e0b',
    },
    'group': {
        type: 'group',
        name: 'Group',
        label: 'Group',
        icon: 'GR',
        color: ['#f59e0b', '#d97706'],
        shadow: '245, 158, 11',
        initialData: {
            customName: 'Group',
            icon: 'GR',
            width: 420,
            height: 260,
            isGroup: true,
            childNodeIds: [],
            inputs: [],
            outputs: [],
        },
        effectColor: '#f59e0b',
    },
    'component': {
        type: 'component',
        name: 'Component',
        label: 'Component',
        icon: '\u{1F9E9}',
        color: ['#60a5fa', '#3b82f6'],
        shadow: '96, 165, 250',
        initialData: {
            customName: 'Component',
            icon: '\u{1F9E9}',
            width: 320,
            inputs: [],
            outputs: [],
        },
        effectColor: '#60a5fa',
    },
};

export const getNodeDefinition = (type: NodeData['type']): NodeDefinition | undefined => {
    return NODE_DEFINITIONS[type];
};

export const getInitialDataForNode = (type: NodeData['type']): Partial<NodeData['data']> => {
    const definition = getNodeDefinition(type);
    return {
        ...BASE_INITIAL_DATA,
        ...(definition ? definition.initialData : {}),
    };
};




